### ISSUE TITLE
DGR - 4. Tabla de Requisitos Funcionales

### ISSUE THREAD

**Issue by alereyleyva** [GDUMA/cuidea#10]
Dejadme por aquí opiniones de los requisitos que he puesto, o nuevos requisitos que querais añadir y los comentamos :+1: 
DGR: https://docs.google.com/document/d/1r3nj5Gb7m_uSbIIV9P8vhlPFY1qTga3bnX7mmJLDzk8/edit?usp=sharing

**Comment by AleReyLeyva** [comment]
Dejadme por aquí opiniones de los requisitos que he puesto, o nuevos requisitos que querais añadir y los comentamos :+1:

**Comment by tomgreef** [comment]
Lo veo todo bien 🚀💪
